---
Name: buckleshusky-fontawesomeiconpicker
---
PageController:
    extensions:
        FontAwesomeIconPicker: 'BucklesHusky\FontAwesomeIconPicker\Extensions\PageControllerExtension'

SilverStripe\Dev\DevBuildController:
  extensions:
    - 'BucklesHusky\FontAwesomeIconPicker\Extensions\FontAwesomeUpdater'

SilverStripe\Core\Injector\Injector:
    Psr\SimpleCache\CacheInterface.fontawesomeiconpicker:
        factory: SilverStripe\Core\Cache\CacheFactory
        constructor:
            namespace: "fontawesomeiconpicker"

SilverStripe\Admin\LeftAndMain:
    extra_requirements_javascript:
        - "buckleshusky/fontawesomeiconpicker: javascript/boot/boot.js"
    extra_requirements_css:
        - "buckleshusky/fontawesomeiconpicker: css/styles.css"
    extensions:
        - BucklesHusky\FontAwesomeIconPicker\Extensions\LeftAndMainExtension
