---
Name: buckleshusky-fontawesomeiconpicker
---
PageController:
  extensions:
    - BucklesHusky\FontAwesomeIconPicker\Extensions\PageControllerExtension

SilverStripe\Admin\LeftAndMain:
  extensions:
    - BucklesHusky\FontAwesomeIconPicker\Extensions\LeftAndMainExtension

FontawesomeIcons:
  version: "5.14.0"

SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.fontawesomeiconpicker:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "fontawesomeiconpicker"