---
Name: buckleshusky-fontawesomeiconpicker
---
PageController:
    extensions:
        - BucklesHusky\FontAwesomeIconPicker\Extensions\PageControllerExtension

FontawesomeIcons:
    version: "5.14.0"

SilverStripe\Core\Injector\Injector:
    Psr\SimpleCache\CacheInterface.fontawesomeiconpicker:
        factory: SilverStripe\Core\Cache\CacheFactory
        constructor:
            namespace: "fontawesomeiconpicker"

SilverStripe\Admin\LeftAndMain:
    extra_requirements_javascript:
        - "buckleshusky/fontawesomeiconpicker: javascript/boot/boot.js"
    extra_requirements_css:
        - "buckleshusky/fontawesomeiconpicker: css/styles.css"
