---
Name: buckleshusky-fontawesomeiconpicker
---
PageController:
  extensions:
    - BucklesHusky\FontAwesomeIconPicker\Extensions\PageControllerExtension

SilverStripe\Admin\LeftAndMain:
  extensions:
    - BucklesHusky\FontAwesomeIconPicker\Extensions\LeftAndMainExtension

FontawesomeIcons:
  version: "5.12.1"
